apiVersion: apps/v1
kind: Deployment
metadata:
  name: td3r507-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: td3r507
  template:
    metadata:
      labels:
        app: td3r507
    spec:
      containers:
        - name: td3r507-container
          image: lucaswllnr/td3r507
          ports:
            - containerPort: 5000
