apiVersion: v1
kind: Service
metadata:
  name: td3r507-service
  namespace: default
spec:
  selector:
    app: td3r507
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
